apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: public
  labels:
    app.kubernetes.io/instance: nginx
  name: web-color-ingress
  namespace: web-color
spec:
  rules:
    - host: 172.20.0.8
      http:
        paths:
          - backend:
              serviceName: web-color
              servicePort: 30003
            path: /
